version: '3.8'
services:
  postgres:
    container_name: tourly-postgres
    image: postgres
    environment:
      POSTGRES_USER: tourly
      POSTGRES_PASSWORD: tourly12
      POSTGRES_DB: tourly
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: