services:
  - type: web
    name: tourly-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/skopje-tourism-guide-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_KEY
        sync: false
      - key: AZURE_OPENAI_DEPLOYMENT
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false